- name: 
  hosts: all
  become: true
  vars:
    docker_users:
      - panda
      - vagrant
    docker_daemon_options:
<<<<<<< HEAD
      insecure-registries : ["192.168.44.44:8082"]
=======
      insecure-registries: ["192.168.44.44:8082"]  
>>>>>>> ea74ee7c588b4958cad3abf2bab5559a43167c55
  roles:
    - user
    - packages
    - geerlingguy.docker
    - christiangda.awscli
    - christiangda.awscli_configure
    - diodonfrost.terraform
